apiVersion: v1
kind: Service
metadata:
  name: mihiro10-test-redis-service
  labels:
    username: mihiro10
    env: test
spec:
  type: ClusterIP
  selector:
    app: mihiro10-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379