apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mihiro10-test-redis-pvc
  labels:
    username: mihiro10
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi