apiVersion: apps/v1
kind: Deployment
metadata:
  name: mihiro10-test-flask-deployment
  labels:
    username: mihiro10
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mihiro10-test-flask
  template:
    metadata:
      labels:
        app: mihiro10-test-flask
        username: mihiro10
        env: test
    spec:
      containers:
        - name: flask
          image: mihiro10/gene_api:hw7.1
          imagePullPolicy: Always
          env:
            - name: mihiro10-test-redis-service
              value: mihiro10-test-redis-service
          ports:
            - containerPort: 5000